//! Wave-based parallel hunter coordination.
//!
//! A *wave* is a batch of N concurrent hunter assignments against an
//! engagement. The orchestrator decides how many hunters to spawn and
//! what surfaces each one owns; each hunter writes its own handoff
//! file; the orchestrator merges handoffs when the wave is done.
//!
//! State is filesystem-backed under
//! `./mantishack-<engagement-id>/waves/<wave-number>/`:
//!
//! ```text
//! waves/
//!   1/
//!     assignments.json        # written by mantis_start_wave
//!     handoff-<assign-id>.json  # written by mantis_write_handoff (one per hunter)
//!     merged.json             # written by mantis_merge_wave
//!   2/
//!     ...
//! ```
//!
//! Each hunter writes to its own file, so there is no shared-write
//! contention even when hunters run in parallel. Writes are atomic
//! (temp-file + rename(2) on the same filesystem).
//!
//! The pattern is inspired by Hacker Bob's wave/handoff mechanism
//! (Apache-2.0, Copyright 2026 Michail Vasileiadis and contributors)
//! — see `/NOTICE` for full attribution. The implementation here is
//! independent Rust; no Hacker Bob source was copied.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// A single hunter's slice of work within a wave.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Assignment {
    /// Stable id (ULID). Generated by the server when the wave starts;
    /// hunters must echo this back in their handoff.
    pub id: String,
    /// URLs to probe.
    pub surfaces: Vec<String>,
    /// Suggested vuln classes for the hunter to consider. The hunter
    /// may ignore this list and probe whatever its checklist covers.
    #[serde(default)]
    pub vuln_classes: Vec<String>,
    /// Free-form context from the orchestrator (e.g. "this surface
    /// returned a 307; check the Location target").
    #[serde(default)]
    pub notes: Option<String>,
}

/// What a hunter writes back when it finishes its assignment.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Handoff {
    /// Must match an `Assignment.id` from this wave.
    pub assignment_id: String,
    /// Agent name that produced the handoff (e.g. `mantis-hunter`).
    pub hunter: String,
    /// Unix seconds when the hunter started its work.
    pub started_at_unix: u64,
    /// Unix seconds when the hunter wrote the handoff.
    pub completed_at_unix: u64,
    /// Structured findings the hunter believes are worth flagging.
    #[serde(default)]
    pub findings: Vec<Finding>,
    /// Techniques the hunter tried that didn't pan out. Reporting
    /// these prevents the next wave from re-running them.
    #[serde(default)]
    pub dead_ends: Vec<DeadEnd>,
    /// Coverage notes — list of techniques attempted.
    #[serde(default)]
    pub coverage: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Finding {
    pub title: String,
    pub surface: String,
    /// Severity hint: `info` / `low` / `medium` / `high` / `critical`.
    /// Hunters self-report; the grader (future work) re-rates.
    pub severity: String,
    pub evidence: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct DeadEnd {
    pub surface: String,
    pub technique: String,
    pub reason: String,
}

/// Aggregate written by `mantis_merge_wave`.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct WaveMerge {
    pub wave_number: u32,
    pub merged_at_unix: u64,
    pub assignments_total: u32,
    pub handoffs_received: u32,
    pub handoffs_missing: Vec<String>,
    pub findings_total: u32,
    pub findings_by_severity: BTreeMap<String, u32>,
    pub dead_ends_total: u32,
    pub coverage_total: u32,
    pub findings: Vec<Finding>,
}

/// Per-assignment progress reported by `mantis_wave_status`.
#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct AssignmentStatus {
    pub assignment_id: String,
    /// `pending` until a handoff file exists; `received` once it does.
    pub status: &'static str,
    pub surfaces: Vec<String>,
    pub hunter: Option<String>,
    pub findings_count: u32,
    pub dead_ends_count: u32,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct WaveStatus {
    pub wave_number: u32,
    pub assignments: Vec<AssignmentStatus>,
    pub all_received: bool,
}

// ---------- filesystem helpers ----------

pub fn engagement_dir(engagement_id: &str) -> PathBuf {
    PathBuf::from(format!("./mantishack-{engagement_id}"))
}

pub fn waves_root(engagement_id: &str) -> PathBuf {
    engagement_dir(engagement_id).join("waves")
}

pub fn wave_dir(engagement_id: &str, wave_number: u32) -> PathBuf {
    waves_root(engagement_id).join(wave_number.to_string())
}

pub fn handoff_path(engagement_id: &str, wave_number: u32, assignment_id: &str) -> PathBuf {
    wave_dir(engagement_id, wave_number).join(format!("handoff-{assignment_id}.json"))
}

pub fn assignments_path(engagement_id: &str, wave_number: u32) -> PathBuf {
    wave_dir(engagement_id, wave_number).join("assignments.json")
}

pub fn merged_path(engagement_id: &str, wave_number: u32) -> PathBuf {
    wave_dir(engagement_id, wave_number).join("merged.json")
}

/// Find the next wave number for an engagement. Scans `waves/` and
/// returns `max(existing) + 1`, or `1` if no waves exist yet.
pub fn next_wave_number(engagement_id: &str) -> Result<u32> {
    let dir = waves_root(engagement_id);
    if !dir.exists() {
        return Ok(1);
    }
    let mut max = 0u32;
    for entry in std::fs::read_dir(&dir).with_context(|| format!("read_dir {}", dir.display()))? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        if let Some(n) = entry.file_name().to_str().and_then(|s| s.parse::<u32>().ok()) {
            if n > max {
                max = n;
            }
        }
    }
    Ok(max + 1)
}

/// Atomic write: write to `<path>.tmp`, then `rename` onto `path`.
/// Both files must be on the same filesystem (always true here since
/// we control the path).
pub fn atomic_write(path: &Path, bytes: &[u8]) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create_dir_all {}", parent.display()))?;
    }
    let mut tmp = path.as_os_str().to_owned();
    tmp.push(".tmp");
    let tmp = PathBuf::from(tmp);
    std::fs::write(&tmp, bytes).with_context(|| format!("write {}", tmp.display()))?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("rename {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

pub fn read_assignments(engagement_id: &str, wave_number: u32) -> Result<Vec<Assignment>> {
    let path = assignments_path(engagement_id, wave_number);
    let bytes = std::fs::read(&path)
        .with_context(|| format!("read {} (did this wave ever start?)", path.display()))?;
    let assignments: Vec<Assignment> = serde_json::from_slice(&bytes)
        .with_context(|| format!("parse assignments at {}", path.display()))?;
    Ok(assignments)
}

pub fn read_handoff(engagement_id: &str, wave_number: u32, assignment_id: &str) -> Option<Handoff> {
    let path = handoff_path(engagement_id, wave_number, assignment_id);
    let bytes = std::fs::read(&path).ok()?;
    serde_json::from_slice(&bytes).ok()
}

// ---------- public ops ----------

/// Persist a wave's assignments to disk. Returns the wave_number.
pub fn start_wave(engagement_id: &str, assignments: &[Assignment]) -> Result<u32> {
    if assignments.is_empty() {
        return Err(anyhow!("assignments must contain at least one entry"));
    }
    let wave_number = next_wave_number(engagement_id)?;
    let bytes =
        serde_json::to_vec_pretty(assignments).context("serialize assignments to JSON")?;
    atomic_write(&assignments_path(engagement_id, wave_number), &bytes)?;
    Ok(wave_number)
}

/// Persist a hunter's handoff. Fails if `assignment_id` is not in the
/// wave's assignments.json (prevents stray writes).
pub fn write_handoff(engagement_id: &str, wave_number: u32, handoff: &Handoff) -> Result<()> {
    let assignments = read_assignments(engagement_id, wave_number)?;
    if !assignments.iter().any(|a| a.id == handoff.assignment_id) {
        return Err(anyhow!(
            "assignment_id `{}` is not part of wave {wave_number}; \
             expected one of: {:?}",
            handoff.assignment_id,
            assignments.iter().map(|a| &a.id).collect::<Vec<_>>()
        ));
    }
    let bytes = serde_json::to_vec_pretty(handoff).context("serialize handoff")?;
    atomic_write(
        &handoff_path(engagement_id, wave_number, &handoff.assignment_id),
        &bytes,
    )?;
    Ok(())
}

/// Report per-assignment status. Cheap; reads each handoff file.
pub fn wave_status(engagement_id: &str, wave_number: u32) -> Result<WaveStatus> {
    let assignments = read_assignments(engagement_id, wave_number)?;
    let mut out = Vec::with_capacity(assignments.len());
    for a in &assignments {
        match read_handoff(engagement_id, wave_number, &a.id) {
            Some(h) => out.push(AssignmentStatus {
                assignment_id: a.id.clone(),
                status: "received",
                surfaces: a.surfaces.clone(),
                hunter: Some(h.hunter),
                findings_count: h.findings.len() as u32,
                dead_ends_count: h.dead_ends.len() as u32,
            }),
            None => out.push(AssignmentStatus {
                assignment_id: a.id.clone(),
                status: "pending",
                surfaces: a.surfaces.clone(),
                hunter: None,
                findings_count: 0,
                dead_ends_count: 0,
            }),
        }
    }
    let all_received = out.iter().all(|s| s.status == "received");
    Ok(WaveStatus {
        wave_number,
        assignments: out,
        all_received,
    })
}

/// Aggregate every handoff that has landed into one merged record and
/// write it to `merged.json`.
pub fn merge_wave(engagement_id: &str, wave_number: u32) -> Result<WaveMerge> {
    let assignments = read_assignments(engagement_id, wave_number)?;
    let mut received = 0u32;
    let mut missing = Vec::new();
    let mut findings: Vec<Finding> = Vec::new();
    let mut dead_ends_total = 0u32;
    let mut coverage_total = 0u32;
    let mut by_sev: BTreeMap<String, u32> = BTreeMap::new();

    for a in &assignments {
        match read_handoff(engagement_id, wave_number, &a.id) {
            Some(h) => {
                received += 1;
                dead_ends_total += h.dead_ends.len() as u32;
                coverage_total += h.coverage.len() as u32;
                for f in &h.findings {
                    *by_sev.entry(f.severity.clone()).or_default() += 1;
                }
                findings.extend(h.findings);
            }
            None => missing.push(a.id.clone()),
        }
    }

    let merged_at_unix = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    let merge = WaveMerge {
        wave_number,
        merged_at_unix,
        assignments_total: assignments.len() as u32,
        handoffs_received: received,
        handoffs_missing: missing,
        findings_total: findings.len() as u32,
        findings_by_severity: by_sev,
        dead_ends_total,
        coverage_total,
        findings,
    };
    let bytes = serde_json::to_vec_pretty(&merge).context("serialize merged.json")?;
    atomic_write(&merged_path(engagement_id, wave_number), &bytes)?;
    Ok(merge)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    // Tests use a per-test temp dir as cwd to avoid polluting the
    // workspace. cwd is process-global so the tests must be
    // serialized; a single mutex is enough.
    static CWD_LOCK: Mutex<()> = Mutex::new(());

    struct CwdGuard {
        prev: PathBuf,
        _g: std::sync::MutexGuard<'static, ()>,
    }
    impl CwdGuard {
        fn new(new_cwd: &Path) -> Self {
            let g = CWD_LOCK.lock().unwrap();
            let prev = std::env::current_dir().unwrap();
            std::env::set_current_dir(new_cwd).unwrap();
            Self { prev, _g: g }
        }
    }
    impl Drop for CwdGuard {
        fn drop(&mut self) {
            let _ = std::env::set_current_dir(&self.prev);
        }
    }

    fn sample_assignment(id: &str, url: &str) -> Assignment {
        Assignment {
            id: id.into(),
            surfaces: vec![url.into()],
            vuln_classes: vec!["auth".into()],
            notes: None,
        }
    }

    fn sample_handoff(assignment_id: &str, findings: Vec<Finding>) -> Handoff {
        Handoff {
            assignment_id: assignment_id.into(),
            hunter: "mantis-hunter".into(),
            started_at_unix: 0,
            completed_at_unix: 1,
            findings,
            dead_ends: vec![],
            coverage: vec!["robots".into(), "sitemap".into()],
        }
    }

    fn finding(title: &str, sev: &str) -> Finding {
        Finding {
            title: title.into(),
            surface: "https://x.example/".into(),
            severity: sev.into(),
            evidence: "stub".into(),
        }
    }

    #[test]
    fn next_wave_starts_at_one_then_increments() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0000000000000000";
        assert_eq!(next_wave_number(eng).unwrap(), 1);

        start_wave(eng, &[sample_assignment("a1", "https://x.example/")]).unwrap();
        assert_eq!(next_wave_number(eng).unwrap(), 2);

        start_wave(eng, &[sample_assignment("b1", "https://y.example/")]).unwrap();
        assert_eq!(next_wave_number(eng).unwrap(), 3);
    }

    #[test]
    fn atomic_write_creates_parent_and_overwrites() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("a/b/c.json");
        atomic_write(&target, b"v1").unwrap();
        assert_eq!(std::fs::read(&target).unwrap(), b"v1");
        atomic_write(&target, b"v2").unwrap();
        assert_eq!(std::fs::read(&target).unwrap(), b"v2");
    }

    #[test]
    fn write_handoff_rejects_unknown_assignment_id() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0000000000000001";
        start_wave(eng, &[sample_assignment("known", "https://x.example/")]).unwrap();

        let err = write_handoff(eng, 1, &sample_handoff("unknown", vec![])).unwrap_err();
        let msg = format!("{err}");
        assert!(msg.contains("unknown"), "msg: {msg}");
    }

    #[test]
    fn status_distinguishes_pending_and_received() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0000000000000002";
        start_wave(
            eng,
            &[
                sample_assignment("a1", "https://a.example/"),
                sample_assignment("a2", "https://b.example/"),
            ],
        )
        .unwrap();

        write_handoff(eng, 1, &sample_handoff("a1", vec![finding("x", "low")])).unwrap();

        let status = wave_status(eng, 1).unwrap();
        assert_eq!(status.wave_number, 1);
        assert_eq!(status.assignments.len(), 2);
        assert!(!status.all_received);
        let a1 = status.assignments.iter().find(|s| s.assignment_id == "a1").unwrap();
        assert_eq!(a1.status, "received");
        assert_eq!(a1.findings_count, 1);
        let a2 = status.assignments.iter().find(|s| s.assignment_id == "a2").unwrap();
        assert_eq!(a2.status, "pending");
        assert_eq!(a2.findings_count, 0);
    }

    #[test]
    fn merge_aggregates_findings_and_reports_missing() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0000000000000003";
        start_wave(
            eng,
            &[
                sample_assignment("a1", "https://a.example/"),
                sample_assignment("a2", "https://b.example/"),
                sample_assignment("a3", "https://c.example/"),
            ],
        )
        .unwrap();

        write_handoff(
            eng,
            1,
            &sample_handoff(
                "a1",
                vec![
                    finding("auth-bypass", "high"),
                    finding("info-disclosure", "low"),
                ],
            ),
        )
        .unwrap();
        write_handoff(
            eng,
            1,
            &sample_handoff("a2", vec![finding("ssrf", "high")]),
        )
        .unwrap();

        let merge = merge_wave(eng, 1).unwrap();
        assert_eq!(merge.assignments_total, 3);
        assert_eq!(merge.handoffs_received, 2);
        assert_eq!(merge.handoffs_missing, vec!["a3".to_string()]);
        assert_eq!(merge.findings_total, 3);
        assert_eq!(merge.findings_by_severity.get("high").copied(), Some(2));
        assert_eq!(merge.findings_by_severity.get("low").copied(), Some(1));
        assert_eq!(merge.dead_ends_total, 0);
        // coverage = 2 per handoff * 2 handoffs
        assert_eq!(merge.coverage_total, 4);

        // merged.json was written
        let bytes = std::fs::read(merged_path(eng, 1)).unwrap();
        let parsed: WaveMerge = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(parsed.findings_total, 3);
    }
}
