//! Wave-based parallel hunter coordination.
//!
//! # Apache-2.0 §4(b) notice — derivative work
//!
//! Portions of this file are derived from Hacker Bob
//! (<https://github.com/vmihalis/hacker-bob>), Copyright 2026 Michail
//! Vasileiadis, licensed under the Apache License, Version 2.0. The
//! `ChainAttemptOutcome` enum and the severity-ladder rules
//! (`LOW + LOW = LOW`, max(input)+1 without rationale, max(input)+2
//! with explicit `elevation:` rationale, no jump-the-rung) are ported
//! verbatim from Hacker Bob's `prompts/roles/chain.md` and
//! `mcp/lib/chain-attempts.js`. The surrounding Rust implementation
//! (filesystem layout, atomic writes, the wave orchestration tools)
//! is independent and was written from scratch.
//!
//! See the project NOTICE for the upstream attribution and the
//! compliance-history apology. This notice is provided per
//! Apache-2.0 §4(b) ("You must cause any modified files to carry
//! prominent notices stating that You changed the files").
//!
//! # Wave protocol
//!
//! A *wave* is a batch of N concurrent hunter assignments against an
//! engagement. The orchestrator decides how many hunters to spawn and
//! what surfaces each one owns; each hunter writes its own handoff
//! file; the orchestrator merges handoffs when the wave is done.
//!
//! State is filesystem-backed under
//! `./mantishack-<engagement-id>/waves/<wave-number>/`:
//!
//! ```text
//! waves/
//!   1/
//!     assignments.json        # written by mantis_start_wave
//!     handoff-<assign-id>.json  # written by mantis_write_handoff (one per hunter)
//!     merged.json             # written by mantis_merge_wave
//!   2/
//!     ...
//! ```
//!
//! Each hunter writes to its own file, so there is no shared-write
//! contention even when hunters run in parallel. Writes are atomic
//! (temp-file + rename(2) on the same filesystem).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// A single hunter's slice of work within a wave.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Assignment {
    /// Stable id (ULID). Generated by the server when the wave starts;
    /// hunters must echo this back in their handoff.
    pub id: String,
    /// URLs to probe.
    pub surfaces: Vec<String>,
    /// Suggested vuln classes for the hunter to consider. The hunter
    /// may ignore this list and probe whatever its checklist covers.
    #[serde(default)]
    pub vuln_classes: Vec<String>,
    /// Free-form context from the orchestrator (e.g. "this surface
    /// returned a 307; check the Location target").
    #[serde(default)]
    pub notes: Option<String>,
}

/// What a hunter writes back when it finishes its assignment.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Handoff {
    /// Must match an `Assignment.id` from this wave.
    pub assignment_id: String,
    /// Agent name that produced the handoff (e.g. `mantis-hunter`).
    pub hunter: String,
    /// Unix seconds when the hunter started its work.
    pub started_at_unix: u64,
    /// Unix seconds when the hunter wrote the handoff.
    pub completed_at_unix: u64,
    /// Structured findings the hunter believes are worth flagging.
    #[serde(default)]
    pub findings: Vec<Finding>,
    /// Techniques the hunter tried that didn't pan out. Reporting
    /// these prevents the next wave from re-running them.
    #[serde(default)]
    pub dead_ends: Vec<DeadEnd>,
    /// Coverage notes — list of techniques attempted.
    #[serde(default)]
    pub coverage: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Finding {
    pub title: String,
    pub surface: String,
    /// Severity hint: `info` / `low` / `medium` / `high` / `critical`.
    /// Hunters self-report; the grader (future work) re-rates.
    pub severity: String,
    pub evidence: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct DeadEnd {
    pub surface: String,
    pub technique: String,
    pub reason: String,
}

/// A chain attempt — a recorded hypothesis that one finding enables
/// another, with an explicit outcome.
///
/// As of the independence transition (see
/// [`docs/ARCHITECTURE_RENAME_PROPOSAL.md`](../../../docs/ARCHITECTURE_RENAME_PROPOSAL.md)),
/// the canonical outcome vocabulary is the Mantis-native set:
/// `Verified` / `Refuted` / `Gated` / `Unresolved` / `OutOfScope`.
///
/// During the transition window, the older lowercase set
/// (`confirmed` / `denied` / `blocked` / `inconclusive` / `not_applicable`)
/// is also accepted on input for backward compatibility with persisted
/// JSONL files written before the rename landed. New writes should use
/// the canonical Mantis-native names. The
/// [`canonicalize_outcome`] helper maps any accepted form to the
/// canonical Mantis-native form for callers that want the normalized
/// value.
///
/// The severity ladder enforced here is the legacy ladder (LOW+LOW=LOW,
/// `max input + 1` without rationale, `max input + 2` with `elevation:`).
/// The redesigned clamp-based ladder proposed in
/// `docs/ARCHITECTURE_RENAME_PROPOSAL.md` §3 lands in a follow-up
/// alongside the full enum refactor.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ChainAttempt {
    /// Short ULID-derived id, generated server-side.
    pub id: String,
    /// `finding_id`s (titles, in our schema) the chain composes.
    pub finding_titles: Vec<String>,
    /// Surface(s) involved.
    pub surfaces: Vec<String>,
    /// One-line narrative: "subdomain takeover -> wallet drain".
    pub hypothesis: String,
    /// Concise replay/rejection steps, one per line.
    pub steps: Vec<String>,
    /// Outcome (enforced server-side). Canonical Mantis-native values:
    /// `Verified`, `Refuted`, `Gated`, `Unresolved`, `OutOfScope`.
    /// Legacy lowercase values (`confirmed`, `denied`, `blocked`,
    /// `inconclusive`, `not_applicable`) are accepted on input for
    /// backward compatibility with pre-transition data; new writes
    /// should use the canonical Mantis-native names.
    pub outcome: String,
    /// Severity of the *composed* chain, max per the ladder rules.
    pub severity: String,
    /// Short prose: "POST /verify accepted stale token; status 200."
    pub evidence_summary: String,
    /// If severity was elevated under a rationale, the operator's
    /// explanation. Required when crossing a ladder rung.
    pub severity_elevation_rationale: Option<String>,
    pub recorded_at_unix: u64,
}

/// Aggregate written by `mantis_merge_wave`.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct WaveMerge {
    pub wave_number: u32,
    pub merged_at_unix: u64,
    pub assignments_total: u32,
    pub handoffs_received: u32,
    pub handoffs_missing: Vec<String>,
    pub findings_total: u32,
    pub findings_by_severity: BTreeMap<String, u32>,
    pub dead_ends_total: u32,
    pub coverage_total: u32,
    pub findings: Vec<Finding>,
}

/// Per-assignment progress reported by `mantis_wave_status`.
#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct AssignmentStatus {
    pub assignment_id: String,
    /// `pending` until a handoff file exists; `received` once it does.
    pub status: &'static str,
    pub surfaces: Vec<String>,
    pub hunter: Option<String>,
    pub findings_count: u32,
    pub dead_ends_count: u32,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct WaveStatus {
    pub wave_number: u32,
    pub assignments: Vec<AssignmentStatus>,
    pub all_received: bool,
}

// ---------- filesystem helpers ----------

pub fn engagement_dir(engagement_id: &str) -> PathBuf {
    PathBuf::from(format!("./mantishack-{engagement_id}"))
}

pub fn waves_root(engagement_id: &str) -> PathBuf {
    engagement_dir(engagement_id).join("waves")
}

pub fn wave_dir(engagement_id: &str, wave_number: u32) -> PathBuf {
    waves_root(engagement_id).join(wave_number.to_string())
}

pub fn handoff_path(engagement_id: &str, wave_number: u32, assignment_id: &str) -> PathBuf {
    wave_dir(engagement_id, wave_number).join(format!("handoff-{assignment_id}.json"))
}

pub fn assignments_path(engagement_id: &str, wave_number: u32) -> PathBuf {
    wave_dir(engagement_id, wave_number).join("assignments.json")
}

pub fn merged_path(engagement_id: &str, wave_number: u32) -> PathBuf {
    wave_dir(engagement_id, wave_number).join("merged.json")
}

pub fn chain_attempts_path(engagement_id: &str, wave_number: u32) -> PathBuf {
    wave_dir(engagement_id, wave_number).join("chain-attempts.jsonl")
}

/// Canonical Mantis-native chain-outcome values. Output of
/// [`canonicalize_outcome`] is always one of these.
pub const CHAIN_OUTCOMES_CANONICAL: &[&str] = &[
    "Verified",
    "Refuted",
    "Gated",
    "Unresolved",
    "OutOfScope",
];

/// Legacy chain-outcome values from the pre-transition Hacker-Bob-derived
/// vocabulary. Accepted on input for backward compatibility with persisted
/// JSONL files written before the rename. NOT for use in new writes —
/// new code should emit canonical values from [`CHAIN_OUTCOMES_CANONICAL`].
pub const CHAIN_OUTCOMES_LEGACY: &[&str] = &[
    "confirmed",
    "denied",
    "blocked",
    "inconclusive",
    "not_applicable",
];

/// Union of canonical + legacy outcomes for validation purposes.
const CHAIN_OUTCOMES: &[&str] = &[
    // Canonical Mantis-native
    "Verified",
    "Refuted",
    "Gated",
    "Unresolved",
    "OutOfScope",
    // Legacy (pre-transition); accepted on input only.
    "confirmed",
    "denied",
    "blocked",
    "inconclusive",
    "not_applicable",
];

/// Map any accepted outcome value (canonical or legacy) to its canonical
/// Mantis-native form. Returns `None` for unknown values.
///
/// Use this when normalizing data from persisted storage so downstream
/// consumers don't need to handle both vocabularies.
pub fn canonicalize_outcome(outcome: &str) -> Option<&'static str> {
    match outcome {
        "Verified" | "confirmed" => Some("Verified"),
        "Refuted" | "denied" => Some("Refuted"),
        "Gated" | "blocked" => Some("Gated"),
        "Unresolved" | "inconclusive" => Some("Unresolved"),
        "OutOfScope" | "not_applicable" => Some("OutOfScope"),
        _ => None,
    }
}

const SEVERITY_RANK: &[(&str, u8)] = &[
    ("info", 0),
    ("low", 1),
    ("medium", 2),
    ("high", 3),
    ("critical", 4),
];

fn severity_rank(s: &str) -> Option<u8> {
    SEVERITY_RANK.iter().find(|(k, _)| *k == s).map(|(_, v)| *v)
}

/// Validate the chain-attempt against the severity ladder. Returns
/// the validated severity string. Rules from
/// `plugin/claude-code/playbooks/README.md`:
///
/// - `severity` must be one of `info/low/medium/high/critical`.
/// - `severity` cannot exceed `max(input_severities) + 1` unless
///   `severity_elevation_rationale` is non-empty.
/// - Even with rationale, `severity` cannot exceed
///   `max(input_severities) + 2` (no jumping rungs).
/// - If `severity` exceeds `max(input_severities)`, the rationale
///   must mention "elevation:" so it is searchable.
pub fn validate_chain_severity(
    severity: &str,
    input_severities: &[String],
    rationale: Option<&str>,
) -> Result<()> {
    let chain_rank = severity_rank(severity)
        .ok_or_else(|| anyhow!("severity must be one of info/low/medium/high/critical"))?;
    let max_input = input_severities
        .iter()
        .filter_map(|s| severity_rank(s))
        .max()
        .unwrap_or(0);
    if chain_rank <= max_input {
        return Ok(());
    }
    let step = chain_rank - max_input;
    if step >= 3 {
        return Err(anyhow!(
            "chain severity `{severity}` is {step} rungs above input max — \
             jumping rungs is forbidden under any rationale"
        ));
    }
    let rationale = rationale.unwrap_or("").trim();
    if rationale.is_empty() {
        return Err(anyhow!(
            "chain severity `{severity}` exceeds input max by {step} rung(s); \
             severity_elevation_rationale is required"
        ));
    }
    if step >= 2 && !rationale.to_lowercase().contains("elevation:") {
        return Err(anyhow!(
            "chain severity jumps {step} rungs; rationale must contain the \
             token `elevation:` describing the multiplier"
        ));
    }
    Ok(())
}

pub fn validate_chain_outcome(outcome: &str) -> Result<()> {
    if !CHAIN_OUTCOMES.contains(&outcome) {
        return Err(anyhow!(
            "outcome `{outcome}` invalid; must be one of: {}",
            CHAIN_OUTCOMES.join(", ")
        ));
    }
    Ok(())
}

/// Append a chain attempt to `waves/<n>/chain-attempts.jsonl`.
///
/// Uses `O_APPEND` writes so concurrent recorders cannot clobber each
/// other. On Unix, a single `write(2)` call of bytes <= `PIPE_BUF`
/// (typically 4096) is atomic on an O_APPEND-opened file, which is
/// well above the size of a serialized `ChainAttempt`. The earlier
/// read-then-atomic-rename implementation lost concurrent records
/// when multiple tool calls raced (the rename target only allows one
/// winner).
pub fn record_chain_attempt(
    engagement_id: &str,
    wave_number: u32,
    attempt: &ChainAttempt,
) -> Result<()> {
    use std::io::Write;
    validate_chain_outcome(&attempt.outcome)?;
    let path = chain_attempts_path(engagement_id, wave_number);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create_dir_all {}", parent.display()))?;
    }
    let mut line = serde_json::to_string(attempt).context("serialize chain attempt")?;
    line.push('\n');
    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&path)
        .with_context(|| format!("open {} for append", path.display()))?;
    file.write_all(line.as_bytes())
        .with_context(|| format!("append to {}", path.display()))?;
    Ok(())
}

pub fn read_chain_attempts(engagement_id: &str, wave_number: u32) -> Vec<ChainAttempt> {
    let path = chain_attempts_path(engagement_id, wave_number);
    let Ok(bytes) = std::fs::read(&path) else {
        return Vec::new();
    };
    let text = String::from_utf8_lossy(&bytes);
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .filter_map(|l| serde_json::from_str::<ChainAttempt>(l).ok())
        .collect()
}

/// Find the next wave number for an engagement. Scans `waves/` and
/// returns `max(existing) + 1`, or `1` if no waves exist yet.
pub fn next_wave_number(engagement_id: &str) -> Result<u32> {
    let dir = waves_root(engagement_id);
    if !dir.exists() {
        return Ok(1);
    }
    let mut max = 0u32;
    for entry in std::fs::read_dir(&dir).with_context(|| format!("read_dir {}", dir.display()))? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        if let Some(n) = entry
            .file_name()
            .to_str()
            .and_then(|s| s.parse::<u32>().ok())
        {
            if n > max {
                max = n;
            }
        }
    }
    Ok(max + 1)
}

/// Atomic write: write to `<path>.tmp`, then `rename` onto `path`.
/// Both files must be on the same filesystem (always true here since
/// we control the path).
pub fn atomic_write(path: &Path, bytes: &[u8]) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create_dir_all {}", parent.display()))?;
    }
    let mut tmp = path.as_os_str().to_owned();
    tmp.push(".tmp");
    let tmp = PathBuf::from(tmp);
    std::fs::write(&tmp, bytes).with_context(|| format!("write {}", tmp.display()))?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("rename {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

pub fn read_assignments(engagement_id: &str, wave_number: u32) -> Result<Vec<Assignment>> {
    let path = assignments_path(engagement_id, wave_number);
    let bytes = std::fs::read(&path)
        .with_context(|| format!("read {} (did this wave ever start?)", path.display()))?;
    let assignments: Vec<Assignment> = serde_json::from_slice(&bytes)
        .with_context(|| format!("parse assignments at {}", path.display()))?;
    Ok(assignments)
}

pub fn read_handoff(engagement_id: &str, wave_number: u32, assignment_id: &str) -> Option<Handoff> {
    let path = handoff_path(engagement_id, wave_number, assignment_id);
    let bytes = std::fs::read(&path).ok()?;
    serde_json::from_slice(&bytes).ok()
}

// ---------- public ops ----------

/// Persist a wave's assignments to disk. Returns the wave_number.
pub fn start_wave(engagement_id: &str, assignments: &[Assignment]) -> Result<u32> {
    if assignments.is_empty() {
        return Err(anyhow!("assignments must contain at least one entry"));
    }
    let wave_number = next_wave_number(engagement_id)?;
    let bytes = serde_json::to_vec_pretty(assignments).context("serialize assignments to JSON")?;
    atomic_write(&assignments_path(engagement_id, wave_number), &bytes)?;
    Ok(wave_number)
}

/// Persist a hunter's handoff. Fails if `assignment_id` is not in the
/// wave's assignments.json (prevents stray writes).
pub fn write_handoff(engagement_id: &str, wave_number: u32, handoff: &Handoff) -> Result<()> {
    let assignments = read_assignments(engagement_id, wave_number)?;
    if !assignments.iter().any(|a| a.id == handoff.assignment_id) {
        return Err(anyhow!(
            "assignment_id `{}` is not part of wave {wave_number}; \
             expected one of: {:?}",
            handoff.assignment_id,
            assignments.iter().map(|a| &a.id).collect::<Vec<_>>()
        ));
    }
    let bytes = serde_json::to_vec_pretty(handoff).context("serialize handoff")?;
    atomic_write(
        &handoff_path(engagement_id, wave_number, &handoff.assignment_id),
        &bytes,
    )?;
    Ok(())
}

/// Report per-assignment status. Cheap; reads each handoff file.
pub fn wave_status(engagement_id: &str, wave_number: u32) -> Result<WaveStatus> {
    let assignments = read_assignments(engagement_id, wave_number)?;
    let mut out = Vec::with_capacity(assignments.len());
    for a in &assignments {
        match read_handoff(engagement_id, wave_number, &a.id) {
            Some(h) => out.push(AssignmentStatus {
                assignment_id: a.id.clone(),
                status: "received",
                surfaces: a.surfaces.clone(),
                hunter: Some(h.hunter),
                findings_count: h.findings.len() as u32,
                dead_ends_count: h.dead_ends.len() as u32,
            }),
            None => out.push(AssignmentStatus {
                assignment_id: a.id.clone(),
                status: "pending",
                surfaces: a.surfaces.clone(),
                hunter: None,
                findings_count: 0,
                dead_ends_count: 0,
            }),
        }
    }
    let all_received = out.iter().all(|s| s.status == "received");
    Ok(WaveStatus {
        wave_number,
        assignments: out,
        all_received,
    })
}

/// Aggregate every handoff that has landed into one merged record and
/// write it to `merged.json`.
pub fn merge_wave(engagement_id: &str, wave_number: u32) -> Result<WaveMerge> {
    let assignments = read_assignments(engagement_id, wave_number)?;
    let mut received = 0u32;
    let mut missing = Vec::new();
    let mut findings: Vec<Finding> = Vec::new();
    let mut dead_ends_total = 0u32;
    let mut coverage_total = 0u32;
    let mut by_sev: BTreeMap<String, u32> = BTreeMap::new();

    for a in &assignments {
        match read_handoff(engagement_id, wave_number, &a.id) {
            Some(h) => {
                received += 1;
                dead_ends_total += h.dead_ends.len() as u32;
                coverage_total += h.coverage.len() as u32;
                for f in &h.findings {
                    *by_sev.entry(f.severity.clone()).or_default() += 1;
                }
                findings.extend(h.findings);
            }
            None => missing.push(a.id.clone()),
        }
    }

    let merged_at_unix = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    let merge = WaveMerge {
        wave_number,
        merged_at_unix,
        assignments_total: assignments.len() as u32,
        handoffs_received: received,
        handoffs_missing: missing,
        findings_total: findings.len() as u32,
        findings_by_severity: by_sev,
        dead_ends_total,
        coverage_total,
        findings,
    };
    let bytes = serde_json::to_vec_pretty(&merge).context("serialize merged.json")?;
    atomic_write(&merged_path(engagement_id, wave_number), &bytes)?;
    Ok(merge)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    // Tests use a per-test temp dir as cwd to avoid polluting the
    // workspace. cwd is process-global so the tests must be
    // serialized; a single mutex is enough.
    static CWD_LOCK: Mutex<()> = Mutex::new(());

    struct CwdGuard {
        prev: PathBuf,
        _g: std::sync::MutexGuard<'static, ()>,
    }
    impl CwdGuard {
        fn new(new_cwd: &Path) -> Self {
            let g = CWD_LOCK.lock().unwrap();
            let prev = std::env::current_dir().unwrap();
            std::env::set_current_dir(new_cwd).unwrap();
            Self { prev, _g: g }
        }
    }
    impl Drop for CwdGuard {
        fn drop(&mut self) {
            let _ = std::env::set_current_dir(&self.prev);
        }
    }

    fn sample_assignment(id: &str, url: &str) -> Assignment {
        Assignment {
            id: id.into(),
            surfaces: vec![url.into()],
            vuln_classes: vec!["auth".into()],
            notes: None,
        }
    }

    fn sample_handoff(assignment_id: &str, findings: Vec<Finding>) -> Handoff {
        Handoff {
            assignment_id: assignment_id.into(),
            hunter: "mantis-hunter".into(),
            started_at_unix: 0,
            completed_at_unix: 1,
            findings,
            dead_ends: vec![],
            coverage: vec!["robots".into(), "sitemap".into()],
        }
    }

    fn finding(title: &str, sev: &str) -> Finding {
        Finding {
            title: title.into(),
            surface: "https://x.example/".into(),
            severity: sev.into(),
            evidence: "stub".into(),
        }
    }

    #[test]
    fn next_wave_starts_at_one_then_increments() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0000000000000000";
        assert_eq!(next_wave_number(eng).unwrap(), 1);

        start_wave(eng, &[sample_assignment("a1", "https://x.example/")]).unwrap();
        assert_eq!(next_wave_number(eng).unwrap(), 2);

        start_wave(eng, &[sample_assignment("b1", "https://y.example/")]).unwrap();
        assert_eq!(next_wave_number(eng).unwrap(), 3);
    }

    #[test]
    fn atomic_write_creates_parent_and_overwrites() {
        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("a/b/c.json");
        atomic_write(&target, b"v1").unwrap();
        assert_eq!(std::fs::read(&target).unwrap(), b"v1");
        atomic_write(&target, b"v2").unwrap();
        assert_eq!(std::fs::read(&target).unwrap(), b"v2");
    }

    #[test]
    fn write_handoff_rejects_unknown_assignment_id() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0000000000000001";
        start_wave(eng, &[sample_assignment("known", "https://x.example/")]).unwrap();

        let err = write_handoff(eng, 1, &sample_handoff("unknown", vec![])).unwrap_err();
        let msg = format!("{err}");
        assert!(msg.contains("unknown"), "msg: {msg}");
    }

    #[test]
    fn status_distinguishes_pending_and_received() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0000000000000002";
        start_wave(
            eng,
            &[
                sample_assignment("a1", "https://a.example/"),
                sample_assignment("a2", "https://b.example/"),
            ],
        )
        .unwrap();

        write_handoff(eng, 1, &sample_handoff("a1", vec![finding("x", "low")])).unwrap();

        let status = wave_status(eng, 1).unwrap();
        assert_eq!(status.wave_number, 1);
        assert_eq!(status.assignments.len(), 2);
        assert!(!status.all_received);
        let a1 = status
            .assignments
            .iter()
            .find(|s| s.assignment_id == "a1")
            .unwrap();
        assert_eq!(a1.status, "received");
        assert_eq!(a1.findings_count, 1);
        let a2 = status
            .assignments
            .iter()
            .find(|s| s.assignment_id == "a2")
            .unwrap();
        assert_eq!(a2.status, "pending");
        assert_eq!(a2.findings_count, 0);
    }

    #[test]
    fn ladder_allows_chain_at_or_below_max_input() {
        let inputs = vec!["low".into(), "medium".into()];
        assert!(validate_chain_severity("info", &inputs, None).is_ok());
        assert!(validate_chain_severity("low", &inputs, None).is_ok());
        assert!(validate_chain_severity("medium", &inputs, None).is_ok());
    }

    #[test]
    fn ladder_requires_rationale_for_one_rung_jump() {
        let inputs = vec!["low".into(), "low".into()];
        // low (max=1) + 1 = medium. No rationale -> reject.
        let err = validate_chain_severity("medium", &inputs, None)
            .err()
            .unwrap()
            .to_string();
        assert!(
            err.contains("severity_elevation_rationale is required"),
            "msg: {err}"
        );
        // With any non-empty rationale -> accept.
        assert!(validate_chain_severity("medium", &inputs, Some("matters because X")).is_ok());
    }

    #[test]
    fn ladder_requires_elevation_token_for_two_rung_jump() {
        let inputs = vec!["low".into()];
        // low (max=1) -> high (rank 3) is +2; needs the literal token "elevation:".
        let err = validate_chain_severity("high", &inputs, Some("important stuff"))
            .err()
            .unwrap()
            .to_string();
        assert!(err.contains("elevation:"), "msg: {err}");
        assert!(validate_chain_severity(
            "high",
            &inputs,
            Some("elevation: combining low XSS with broken cookie auth multiplies impact 100x")
        )
        .is_ok());
    }

    #[test]
    fn ladder_forbids_three_rung_jump_under_any_rationale() {
        let inputs = vec!["info".into()];
        // info (0) -> high (3) is 3 rungs; always rejected.
        let err =
            validate_chain_severity("high", &inputs, Some("elevation: this is huge actually"))
                .err()
                .unwrap()
                .to_string();
        assert!(err.contains("jumping rungs"), "msg: {err}");
    }

    #[test]
    fn ladder_rejects_invalid_severity() {
        assert!(validate_chain_severity("urgent", &["low".into()], None).is_err());
    }

    #[test]
    fn outcome_validator_accepts_legacy_terminal_outcomes() {
        // Backward compatibility with persisted JSONL files written
        // before the rename transition. New writes should use the
        // canonical Mantis-native names below.
        for ok in [
            "confirmed",
            "denied",
            "blocked",
            "inconclusive",
            "not_applicable",
        ] {
            assert!(validate_chain_outcome(ok).is_ok(), "rejected `{ok}`");
        }
    }

    #[test]
    fn outcome_validator_accepts_canonical_mantis_native_outcomes() {
        // These are the canonical Mantis-native vocabulary per
        // docs/ARCHITECTURE_RENAME_PROPOSAL.md and used in
        // prompts/roles/chain.md (clean-room rewritten in PR #79).
        for ok in ["Verified", "Refuted", "Gated", "Unresolved", "OutOfScope"] {
            assert!(validate_chain_outcome(ok).is_ok(), "rejected canonical `{ok}`");
        }
    }

    #[test]
    fn outcome_validator_rejects_unknown_outcomes() {
        // Unknown values must still be rejected. The expanded set is
        // exactly canonical + legacy, nothing else.
        for bad in ["maybe", "partial", "verified" /* lowercase */, "REFUTED" /* uppercase */] {
            assert!(
                validate_chain_outcome(bad).is_err(),
                "accepted unknown `{bad}` — should be canonical exact-match only"
            );
        }
    }

    #[test]
    fn canonicalize_maps_legacy_to_mantis_native() {
        // Backward-compat normalization for downstream consumers that
        // want a single vocabulary.
        assert_eq!(canonicalize_outcome("confirmed"), Some("Verified"));
        assert_eq!(canonicalize_outcome("denied"), Some("Refuted"));
        assert_eq!(canonicalize_outcome("blocked"), Some("Gated"));
        assert_eq!(canonicalize_outcome("inconclusive"), Some("Unresolved"));
        assert_eq!(canonicalize_outcome("not_applicable"), Some("OutOfScope"));
    }

    #[test]
    fn canonicalize_idempotent_on_canonical_values() {
        // Canonical values map to themselves.
        assert_eq!(canonicalize_outcome("Verified"), Some("Verified"));
        assert_eq!(canonicalize_outcome("Refuted"), Some("Refuted"));
        assert_eq!(canonicalize_outcome("Gated"), Some("Gated"));
        assert_eq!(canonicalize_outcome("Unresolved"), Some("Unresolved"));
        assert_eq!(canonicalize_outcome("OutOfScope"), Some("OutOfScope"));
    }

    #[test]
    fn canonicalize_returns_none_for_unknown() {
        assert_eq!(canonicalize_outcome("maybe"), None);
        assert_eq!(canonicalize_outcome("partial"), None);
        assert_eq!(canonicalize_outcome(""), None);
    }

    #[test]
    fn canonical_and_legacy_arrays_are_distinct_and_complete() {
        // The two arrays must be the same length (each canonical maps to
        // exactly one legacy and vice versa) and must not share values.
        assert_eq!(CHAIN_OUTCOMES_CANONICAL.len(), CHAIN_OUTCOMES_LEGACY.len());
        for canonical in CHAIN_OUTCOMES_CANONICAL {
            assert!(
                !CHAIN_OUTCOMES_LEGACY.contains(canonical),
                "canonical `{canonical}` overlaps legacy set"
            );
        }
        // Each canonical has a legacy preimage under canonicalize_outcome.
        let preimages_per_canonical: std::collections::HashMap<&str, usize> =
            CHAIN_OUTCOMES_LEGACY
                .iter()
                .filter_map(|legacy| canonicalize_outcome(legacy))
                .fold(std::collections::HashMap::new(), |mut acc, c| {
                    *acc.entry(c).or_insert(0) += 1;
                    acc
                });
        for canonical in CHAIN_OUTCOMES_CANONICAL {
            assert_eq!(
                preimages_per_canonical.get(canonical).copied().unwrap_or(0),
                1,
                "canonical `{canonical}` should have exactly one legacy preimage"
            );
        }
    }

    #[test]
    fn concurrent_chain_attempts_all_persist() {
        // The O_APPEND fix replaced the read-then-atomic-rename impl
        // that lost concurrent records. This test races 8 writers
        // against the same wave path and asserts all 8 land.
        use std::sync::Arc;
        use std::sync::Barrier;
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0RACE000000000000";
        std::fs::create_dir_all(wave_dir(eng, 1)).unwrap();
        let barrier = Arc::new(Barrier::new(8));
        let mut handles = Vec::new();
        for i in 0..8 {
            let b = barrier.clone();
            let eng_s = eng.to_string();
            handles.push(std::thread::spawn(move || {
                // cwd is process-global on Unix; the CwdGuard above
                // already set it for the whole process. Threads
                // inherit. We do NOT touch cwd here.
                b.wait();
                let a = ChainAttempt {
                    id: format!("atmpt-race-{i}"),
                    finding_titles: vec![format!("F{i}")],
                    surfaces: vec![format!("https://x.example/{i}")],
                    hypothesis: format!("race-{i}"),
                    steps: vec![format!("step {i}")],
                    outcome: "denied".into(),
                    severity: "info".into(),
                    evidence_summary: format!("race {i}"),
                    severity_elevation_rationale: None,
                    recorded_at_unix: 0,
                };
                record_chain_attempt(&eng_s, 1, &a).unwrap();
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        let read = read_chain_attempts(eng, 1);
        assert_eq!(
            read.len(),
            8,
            "expected 8 records to persist; got {}",
            read.len()
        );
    }

    #[test]
    fn record_chain_attempt_appends_jsonl_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0CHAIN000000000";
        // assignments.json need not exist for chain attempts; they're
        // per-wave but not gated by assignments.
        std::fs::create_dir_all(wave_dir(eng, 1)).unwrap();

        let a1 = ChainAttempt {
            id: "atmpt-1".into(),
            finding_titles: vec!["F1".into(), "F2".into()],
            surfaces: vec!["https://x.example/".into()],
            hypothesis: "info leak -> IDOR".into(),
            steps: vec![
                "GET /api/me leaked id 7".into(),
                "GET /api/user/8 returned other".into(),
            ],
            outcome: "confirmed".into(),
            severity: "medium".into(),
            evidence_summary: "two-step replay landed".into(),
            severity_elevation_rationale: None,
            recorded_at_unix: 1,
        };
        let a2 = ChainAttempt {
            id: "atmpt-2".into(),
            finding_titles: vec!["F3".into()],
            surfaces: vec!["https://x.example/".into()],
            hypothesis: "no chain".into(),
            steps: vec!["nothing composes".into()],
            outcome: "not_applicable".into(),
            severity: "info".into(),
            evidence_summary: "single finding".into(),
            severity_elevation_rationale: None,
            recorded_at_unix: 2,
        };
        record_chain_attempt(eng, 1, &a1).unwrap();
        record_chain_attempt(eng, 1, &a2).unwrap();

        let read = read_chain_attempts(eng, 1);
        assert_eq!(read.len(), 2);
        assert_eq!(read[0].hypothesis, "info leak -> IDOR");
        assert_eq!(read[1].outcome, "not_applicable");
    }

    #[test]
    fn merge_aggregates_findings_and_reports_missing() {
        let dir = tempfile::tempdir().unwrap();
        let _g = CwdGuard::new(dir.path());
        let eng = "01TESTENG0000000000000003";
        start_wave(
            eng,
            &[
                sample_assignment("a1", "https://a.example/"),
                sample_assignment("a2", "https://b.example/"),
                sample_assignment("a3", "https://c.example/"),
            ],
        )
        .unwrap();

        write_handoff(
            eng,
            1,
            &sample_handoff(
                "a1",
                vec![
                    finding("auth-bypass", "high"),
                    finding("info-disclosure", "low"),
                ],
            ),
        )
        .unwrap();
        write_handoff(eng, 1, &sample_handoff("a2", vec![finding("ssrf", "high")])).unwrap();

        let merge = merge_wave(eng, 1).unwrap();
        assert_eq!(merge.assignments_total, 3);
        assert_eq!(merge.handoffs_received, 2);
        assert_eq!(merge.handoffs_missing, vec!["a3".to_string()]);
        assert_eq!(merge.findings_total, 3);
        assert_eq!(merge.findings_by_severity.get("high").copied(), Some(2));
        assert_eq!(merge.findings_by_severity.get("low").copied(), Some(1));
        assert_eq!(merge.dead_ends_total, 0);
        // coverage = 2 per handoff * 2 handoffs
        assert_eq!(merge.coverage_total, 4);

        // merged.json was written
        let bytes = std::fs::read(merged_path(eng, 1)).unwrap();
        let parsed: WaveMerge = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(parsed.findings_total, 3);
    }
}
