//! Curated wordlists from `danielmiessler/SecLists` (MIT).
//!
//! Three deliberately-small lists that cover the 80% case for the
//! recon / API enumeration crates. For a full sweep, callers should
//! reach for the full SecLists checkout — these are the seeds the
//! built-in pipeline uses when no external corpus is mounted.

/// Common API base paths — discovered + augmented by hand. Used by
/// the API endpoint enumerator + recon path-fuzzer.
pub static COMMON_API_PATHS: &[&str] = &[
    "/api",
    "/api/v1",
    "/api/v2",
    "/api/v3",
    "/v1",
    "/v2",
    "/v3",
    "/rest",
    "/rest/v1",
    "/graphql",
    "/graphiql",
    "/playground",
    "/__graphql",
    "/swagger",
    "/swagger.json",
    "/swagger.yaml",
    "/swagger-ui",
    "/swagger-ui/index.html",
    "/openapi.json",
    "/openapi.yaml",
    "/openapi/v3",
    "/v2/api-docs",
    "/v3/api-docs",
    "/api-docs",
    "/api/docs",
    "/docs",
    "/redoc",
    "/users",
    "/user",
    "/me",
    "/profile",
    "/account",
    "/admin",
    "/admin/api",
    "/admin/users",
    "/internal",
    "/debug",
    "/healthz",
    "/health",
    "/status",
    "/metrics",
    "/_status",
    "/ping",
    "/version",
    "/info",
    "/config",
    "/settings",
    "/login",
    "/logout",
    "/auth",
    "/oauth",
    "/oauth2",
    "/sso",
    "/saml",
    "/token",
    "/refresh",
    "/register",
    "/signup",
    "/reset",
    "/upload",
    "/download",
    "/files",
    "/search",
    "/query",
    "/webhook",
    "/webhooks",
    "/callback",
    "/notifications",
    "/events",
    "/audit",
    "/billing",
    "/payments",
    "/invoices",
    "/orders",
    "/cart",
    "/checkout",
];

/// Common subdomains — feeds the brute-force tier of the recon
/// pipeline when passive sources return nothing useful.
pub static COMMON_SUBDOMAINS: &[&str] = &[
    "www",
    "mail",
    "smtp",
    "pop",
    "pop3",
    "imap",
    "ns1",
    "ns2",
    "dns",
    "mx",
    "ftp",
    "sftp",
    "ssh",
    "vpn",
    "admin",
    "administrator",
    "root",
    "test",
    "staging",
    "stage",
    "dev",
    "develop",
    "development",
    "beta",
    "alpha",
    "preview",
    "preprod",
    "prod",
    "production",
    "qa",
    "uat",
    "demo",
    "api",
    "api-v1",
    "api-v2",
    "apiv1",
    "apiv2",
    "rest",
    "graphql",
    "grpc",
    "internal",
    "intranet",
    "private",
    "secure",
    "shop",
    "store",
    "cdn",
    "static",
    "assets",
    "media",
    "img",
    "images",
    "files",
    "downloads",
    "download",
    "upload",
    "uploads",
    "support",
    "help",
    "kb",
    "wiki",
    "docs",
    "doc",
    "blog",
    "news",
    "status",
    "monitor",
    "monitoring",
    "metrics",
    "grafana",
    "kibana",
    "prometheus",
    "jenkins",
    "ci",
    "build",
    "deploy",
    "git",
    "gitlab",
    "github",
    "bitbucket",
    "jira",
    "confluence",
    "auth",
    "sso",
    "login",
    "id",
    "identity",
    "account",
    "billing",
    "pay",
    "payment",
    "portal",
    "dashboard",
    "app",
    "apps",
    "console",
    "manage",
    "management",
    "ops",
    "devops",
    "sre",
    "k8s",
    "kube",
    "kubernetes",
    "docker",
    "registry",
];

/// Common parameter names — augments OpenAPI-discovered params with
/// the fuzz-friendly defaults.
pub static COMMON_PARAMS: &[&str] = &[
    "id",
    "uid",
    "user",
    "user_id",
    "userId",
    "username",
    "email",
    "name",
    "page",
    "limit",
    "offset",
    "count",
    "from",
    "to",
    "q",
    "query",
    "search",
    "filter",
    "sort",
    "order",
    "type",
    "kind",
    "category",
    "tag",
    "tags",
    "callback",
    "jsonp",
    "redirect",
    "redirect_uri",
    "redirectUri",
    "return",
    "return_url",
    "returnUrl",
    "next",
    "url",
    "uri",
    "target",
    "dest",
    "destination",
    "file",
    "filename",
    "path",
    "dir",
    "folder",
    "include",
    "template",
    "view",
    "format",
    "fmt",
    "lang",
    "locale",
    "debug",
    "test",
    "admin",
    "is_admin",
    "isAdmin",
    "role",
    "token",
    "key",
    "api_key",
    "apikey",
    "access_token",
    "accessToken",
    "secret",
    "password",
    "passwd",
    "pwd",
    "cmd",
    "command",
    "exec",
    "action",
    "method",
    "func",
    "function",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lists_are_non_empty_and_unique() {
        for list in [COMMON_API_PATHS, COMMON_SUBDOMAINS, COMMON_PARAMS] {
            assert!(!list.is_empty());
            let mut sorted: Vec<&&str> = list.iter().collect();
            sorted.sort_unstable();
            let pre = sorted.len();
            sorted.dedup();
            assert_eq!(pre, sorted.len(), "list has duplicates");
        }
    }

    #[test]
    fn api_paths_all_start_with_slash() {
        for p in COMMON_API_PATHS {
            assert!(p.starts_with('/'), "{} should start with /", p);
        }
    }

    #[test]
    fn subdomains_are_hostname_safe() {
        for s in COMMON_SUBDOMAINS {
            for c in s.chars() {
                assert!(c.is_ascii_alphanumeric() || c == '-', "bad char in {}", s);
            }
        }
    }

    #[test]
    fn graphql_and_swagger_paths_present() {
        assert!(COMMON_API_PATHS.contains(&"/graphql"));
        assert!(COMMON_API_PATHS.contains(&"/swagger.json"));
        assert!(COMMON_API_PATHS.contains(&"/openapi.json"));
    }
}
