//! Three-tier escalating execution model.
//!
//! Mantis tries cheap, fixed Rust primitives first. When they miss,
//! it escalates: an LLM writes a one-shot exploit script tailored
//! to the surface; Mantis runs it sandboxed. If THAT misses, the
//! hard tier opens a verifier loop where the LLM iterates on the
//! script until the verifier accepts a finding (or budget exhausts).
//!
//! ```text
//! ┌───────────┐   miss   ┌────────────┐   miss   ┌──────────────┐
//! │   light   │ ────────▶│   medium   │ ────────▶│ hard verifier│
//! │ (Rust)    │          │ (LLM gen)  │          │ (LLM iterate)│
//! └───────────┘  hit ↓   └────────────┘  hit ↓   └──────────────┘
//!                Finding                  Finding         Finding
//! ```
//!
//! Each tier is a [`Tier`] implementor. A [`TieredRunner`] dispatches
//! light → medium → hard in order, short-circuiting on the first
//! finding. The medium and hard tiers depend on an [`LlmCodegen`]
//! trait which the orchestrator wires to whatever LLM provider is
//! configured (`mantis llm probe --provider anthropic` style).

pub mod adapter;
pub mod llm_bridge;
pub mod provider;
pub mod runner;
pub mod tier;
pub mod verifier;

pub use crate::adapter::{LlmCodegen, MockLlm, NullLlm, SandboxRunner, SubprocessSandbox};
pub use crate::llm_bridge::SynthesizerLlmCodegen;
pub use crate::provider::{
    auto_select, build_codegen, build_llm_adapter, llm_signal_present, ProviderKind,
};
pub use crate::runner::{run_tiered, TieredOutcome, TieredRunner};
pub use crate::tier::{Tier, TierKind, TierResult};
pub use crate::verifier::{verify_finding, VerifierVerdict};

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Clone, Error, PartialEq, Eq)]
pub enum TierError {
    #[error("LLM call failed: {0}")]
    Llm(String),
    #[error("sandbox execution failed: {0}")]
    Sandbox(String),
    #[error("hard-tier budget exhausted after {iterations} iterations")]
    BudgetExhausted { iterations: u32 },
    #[error("invalid script returned by LLM: {0}")]
    InvalidScript(String),
}

/// What we're asking the tiered runner to do for a given target +
/// surface. The light tier reads this to pick a primitive; the
/// medium tier feeds it into the LLM prompt.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Probe {
    pub target_url: String,
    /// Free-form description of what we're testing for. The LLM
    /// reads this verbatim. Operator-supplied or generated by the
    /// hypothesis layer. Examples:
    /// - "IDOR on /api/users?userId=<id>"
    /// - "Mass-assignment via PATCH /rest/v1/users"
    /// - "Unauthenticated access to /admin"
    pub objective: String,
    /// Optional auth context. Light tier consults; medium/hard tier
    /// pass to the LLM so it can write authed requests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attacker_profile: Option<mantis_auth::AuthProfile>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub victim_profile: Option<mantis_auth::AuthProfile>,
    /// Max wall-clock seconds for the full escalation chain.
    pub budget_seconds: u32,
}

/// A finding produced by ANY tier. Same shape regardless of
/// whether it came from a Rust primitive or an LLM-written script.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TieredFinding {
    pub tier: TierKind,
    pub vuln_class: String,
    pub severity: String,
    pub url: String,
    pub evidence: String,
    /// When tier == Medium/Hard, this is the LLM-generated script
    /// that produced the finding. None for light tier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub script: Option<String>,
    /// When tier == Hard, the verifier's verdict ID + reasoning.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verifier_verdict: Option<String>,
    /// Number of iterations the hard-tier verifier took to converge
    /// (1 = first attempt accepted).
    #[serde(default)]
    pub hard_iterations: u32,
}
